development:
  adapter: postgresql
  encoding: unicode
  database: car_listing_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: car_listing_test
  pool: 5
  username:
  password:

